chore(backend): Fix lint warning in documentation (#8341)
# Motivation

With the new version of rust (PR
https://github.com/dfinity/oisy-wallet/pull/8180), we have a lint
warning in the documentation:

```
error: item in documentation is missing backticks
   --> src/backend/src/lib.rs:962:59
    |
962 | /// * `ContactNotFound` - If no contact for the proivided contact_id could be found
    |                                                           ^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
    = note: `-D clippy::doc-markdown` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::doc_markdown)]`
help: try
    |
962 - /// * `ContactNotFound` - If no contact for the proivided contact_id could be found
962 + /// * `ContactNotFound` - If no contact for the proivided `contact_id` could be found
    |
```


We fix it here, since the bot is not allowed to change such files.

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>