test(backend): Check candid compatibility (#5786)
Stacked on #5775 

# Motivation
We wish CI to fail if there is an unannounced breaking change in the
backend canister API.

# Changes
- Add a Rust test for compatibility with the production API.
  - Note: This action is NOT run as part of CI in this PR.

# Tests
### Test fails if there is a breaking API change
Right now, the main branch has a breaking change relative to production,
so if we run backend check it should fail:
```
$ ./scripts/test.backend.sh -- --ignored candid
...
running 1 test
test tests::check_candid_interface_compatibility ... FAILED

failures:

---- tests::check_candid_interface_compatibility stdout ----

thread 'tests::check_candid_interface_compatibility' panicked at src/backend/src/tests.rs:18:6:
The proposed canister interface is not compatible with the production interface: CandidError(Custom(Method allow_signing: func (opt AllowSigningRequest) -> (Result_2) is not a subtype of func () -> (Result_2/1)

Caused by:
    0: Subtype fails at function return type
    1: Record field 0: Result_2 is not a subtype of Result_2/1
    2: Variant field Ok: AllowSigningResponse is not a subtype_ of null
    3: record {
         status : AllowSigningStatus;
         challenge_completion : opt ChallengeCompletion;
         allowed_cycles : nat64;
       } is not a subtype of null))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Test passes if there are no breaking changes
If we check against the current canister Wasm instead of production,
tests pass:
```
max@sinkpad:~/dfn/oisy-wallet/branches/breaking-change (3:00:26)$ cp src/backend/backend.did target/ic/candid/backend.ic.did
max@sinkpad:~/dfn/oisy-wallet/branches/breaking-change (3:00:37)$ ./scripts/test.backend.sh -- --ignored candid
...
running 1 test
test tests::check_candid_interface_compatibility ... ok
```