fix(frontend): theme selector system enum discouraged (#4768)
# Motivation

When updating the code in the Svelte v5 branch today a new check error
popped up. It seems that declaring `enum` in `script` tag is discouraged
which we are doing in the `ThemeSelector`.

```
/home/runner/work/oisy-wallet/oisy-wallet/src/frontend/src/lib/components/settings/ThemeSelector.svelte:9:2
Error: TypeScript language features like enums are not natively supported, and their use is generally discouraged. Outside of `<script>` tags, these features are not supported. For use within `<script>` tags, you will need to use a preprocessor to convert it to JavaScript before it gets passed to the Svelte compiler. If you are using `vitePreprocess`, make sure to specifically enable preprocessing script tags (`vitePreprocess({ script: true })`)
https://svelte.dev/e/typescript_invalid_feature (svelte)

	enum SystemTheme {
		SYSTEM = 'system'
	}
	const THEME_VALUES = [...Object.values(Theme), ...Object.values(SystemTheme)];


====================================
svelte-check found 1 error and 0 warnings in 1 file
```

See CI job:
https://github.com/dfinity/oisy-wallet/actions/runs/13367987071/job/37329996783?pr=3929

# Notes

To resolve the issue we can either move the enum to become global or,
not use an enum. I picked the later because I rather like not have it
expose globally but, if you think there is a chance it will become
global someday, maybe we should just move it?

Also note that I did not tested, just modified the code. Someone might
want to have a try.

# Changes

- Replace `System` enum with a `const`

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>