feat(ci): script to check unused i18n keys (#1844)
# Motivation

New script to check if there are unused keys from the `i18n` file.

For dynamic usage it just checks if each part of the key is in the file
AND if somewhere in the file `get(i18n)` is used.
For example:

```typescript
const { auth: authI18n } = get(i18n);
...
toastsError({
  msg: { text: authI18n.error.no_pouh_credential }
});
```

or

```typescript
const {
  init: {
    error: { eth_address_unknown, loading_balance }
  }
} = get(i18n);
```