chore(test): fix missing issuer mock data (#3336)
# Motivation

Spotted mock data that were incomplete.

```
src/frontend/src/tests/lib/utils/credentials.spec.ts:14:6 - error TS2741: Property 'issuer' is missing in type '{ credential_type: { ProofOfUniqueness: null; }; verified_date_timestamp: [bigint]; }' but required in type 'UserCredential'.

14      {
        ~
15       credential_type: { ProofOfUniqueness: null },
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16       verified_date_timestamp: [123456n]
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17      }
   ~~~~~~

  src/declarations/backend/backend.did.d.ts:204:2
    204  issuer: string;
         ~~~~~~
    'issuer' is declared here.
```

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>