fix(frontend): do not set icon for deprecated tokens (#4627)
# Motivation

Since the deprecated SNS tokens have no logo, when we go in the
`ManageTokens` component we receive a warning in the console that the
image is missing:

```bash
SvelteKitError: Not found: /icons/sns/itgqj-7qaaa-aaaaq-aadoa-cai.png
    at resolve (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@sveltejs/kit/src/runtime/server/respond.js:533:13)
    at resolve (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@sveltejs/kit/src/runtime/server/respond.js:333:5)
    at init_promise.#options.hooks.handle (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@sveltejs/kit/src/runtime/server/index.js:76:56)
    at Module.respond (/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@sveltejs/kit/src/runtime/server/respond.js:330:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  status: 404,
  text: 'Not Found'
}
```

# Changes

Do not map the icon for deprecated SNS tokens.

# Tests

Tested manually in local replica and the warning is not there anymore.