build(deps-dev): bump immutable from 5.0.2 to 5.1.2 (#6951)
Bumps [immutable](https://github.com/immutable-js/immutable-js) from
5.0.2 to 5.1.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/immutable-js/immutable-js/releases">immutable's
releases</a>.</em></p>
<blockquote>
<h2>v5.1.2</h2>
<h2>What's Changed</h2>
<ul>
<li>Revert previous assertion as it introduced a regression by by <a
href="https://github.com/giggo1604"><code>@​giggo1604</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2100">immutable-js/immutable-js#2100</a>
and <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in
<a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2102">immutable-js/immutable-js#2102</a></li>
<li>Merge should work with empty record by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2103">immutable-js/immutable-js#2103</a></li>
</ul>
<h3>Tooling</h3>
<ul>
<li>Ensure files are properly builded by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2081">immutable-js/immutable-js#2081</a></li>
<li>Better TypeScript configuration for jest by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2087">immutable-js/immutable-js#2087</a></li>
</ul>
<h3>Documentation</h3>
<ul>
<li>move check-build-output to mjs file by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2082">immutable-js/immutable-js#2082</a></li>
<li>Bump next from 14.2.24 to 14.2.26 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2084">immutable-js/immutable-js#2084</a></li>
<li>Migrate from jasmine-check to fast-check by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2083">immutable-js/immutable-js#2083</a></li>
<li>Add a playground / repl in the documentation by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2089">immutable-js/immutable-js#2089</a></li>
<li>Fix issue with responsive by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2090">immutable-js/immutable-js#2090</a></li>
<li>Dark mode for documentation by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2091">immutable-js/immutable-js#2091</a></li>
<li>Upgrade doc website to next 15 by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2092">immutable-js/immutable-js#2092</a></li>
<li>chore: update type tests by <a
href="https://github.com/mrazauskas"><code>@​mrazauskas</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2093">immutable-js/immutable-js#2093</a></li>
<li>Encode code to / decode code from the URL hash. by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2096">immutable-js/immutable-js#2096</a></li>
<li>extract repl worker script to a proper file by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2097">immutable-js/immutable-js#2097</a></li>
<li>Deep formatter in playground by <a
href="https://github.com/jdeniau"><code>@​jdeniau</code></a> in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2099">immutable-js/immutable-js#2099</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/giggo1604"><code>@​giggo1604</code></a>
made their first contribution in <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2100">immutable-js/immutable-js#2100</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/immutable-js/immutable-js/compare/v5.1.1...v5.1.2">https://github.com/immutable-js/immutable-js/compare/v5.1.1...v5.1.2</a></p>
<h2>v5.1.1</h2>
<h2>What's Changed</h2>
<p>Fix issue in builded types files in 5.1.0 due to cpy-cli upgrade</p>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/immutable-js/immutable-js/compare/v5.1.0...v5.1.1">https://github.com/immutable-js/immutable-js/compare/v5.1.0...v5.1.1</a></p>
<h2>v5.1.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Add shuffle to list <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2066">#2066</a>
by <a href="https://github.com/mazerty"><code>@​mazerty</code></a></li>
<li>TypeScript: Better getIn <code>RetrievePath</code> <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2070">#2070</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Fix <a
href="https://redirect.github.com/immutable-js/immutable-js/issues/1915">#1915</a>
&quot;Converting a Seq to a list causes RangeError (max call size
exceeded)&quot; by <a
href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a> in
<a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2038">#2038</a></li>
<li>TypeScript: Fix proper typings for Seq.concat() <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2040">#2040</a>
by <a
href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a></li>
<li>Fix Uncaught &quot;TypeError: keyPath.slice is not a function&quot;
for ArrayLike method <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2065">#2065</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgrade typescript and typescript-eslint <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2046">#2046</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Upgrade to rollup 4 <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2049">#2049</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/immutable-js/immutable-js/blob/main/CHANGELOG.md">immutable's
changelog</a>.</em></p>
<blockquote>
<h2>5.1.2</h2>
<ul>
<li>Revert previous assertion as it introduced a regression <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2102">#2102</a>
by <a
href="https://github.com/giggo1604"><code>@​giggo1604</code></a></li>
<li>Merge should work with empty record <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2103">#2103</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<h2>5.1.1</h2>
<ul>
<li>Fix type copying</li>
</ul>
<h2>5.1.0</h2>
<ul>
<li>Add shuffle to list <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2066">#2066</a>
by <a href="https://github.com/mazerty"><code>@​mazerty</code></a></li>
<li>TypeScript: Better getIn <code>RetrievePath</code> <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2070">#2070</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Fix <a
href="https://redirect.github.com/immutable-js/immutable-js/issues/1915">#1915</a>
&quot;Converting a Seq to a list causes RangeError (max call size
exceeded)&quot; by <a
href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a> in
<a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2038">#2038</a></li>
<li>TypeScript: Fix proper typings for Seq.concat() <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2040">#2040</a>
by <a
href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a></li>
<li>Fix Uncaught &quot;TypeError: keyPath.slice is not a function&quot;
for ArrayLike method <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2065">#2065</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
<h3>Internal</h3>
<ul>
<li>Upgrade typescript and typescript-eslint <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2046">#2046</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Upgrade to rollup 4 <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2049">#2049</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Start migrating codebase to TypeScript without any runtime change
nor .d.ts change:
<ul>
<li>allow TS files to be compiled in src dir <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2054">#2054</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
</ul>
</li>
<li>add exception for code that should not happen in updateIn <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2074">#2074</a>
by <a href="https://github.com/jdeniau"><code>@​jdeniau</code></a></li>
<li>Reformat Range.toString for readability <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2075">#2075</a>
by <a
href="https://github.com/ustinvaskin"><code>@​Ustin.Vaskin</code></a></li>
</ul>
<h2>[5.0.3]</h2>
<ul>
<li>Fix List.VNode.removeAfter() / removeBefore() issue on some
particular case <a
href="https://redirect.github.com/immutable-js/immutable-js/pull/2030">#2030</a>
by <a
href="https://github.com/alexvictoor"><code>@​alexvictoor</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/e8106161fea7256d6f390dc646a2920473c2fd7b"><code>e810616</code></a>
5.1.2</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/d5bae7677bbc853e025984b5d0ca57603c86946f"><code>d5bae76</code></a>
changelog</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/ec2ba80fe791f58ffbc0930d357f2712b2baed45"><code>ec2ba80</code></a>
Merge pull request <a
href="https://redirect.github.com/immutable-js/immutable-js/issues/2103">#2103</a>
from immutable-js/merge-empty-record</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/d51af778d4370286e3b6109c33cb042d515ae061"><code>d51af77</code></a>
Merge should work with empty record</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/29431bd51516fa72dbc656a3e32a31cdb3d7db7b"><code>29431bd</code></a>
Merge pull request <a
href="https://redirect.github.com/immutable-js/immutable-js/issues/2102">#2102</a>
from immutable-js/giggo1604-main</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/435adeebd673b7acd545bc14b0063cf2f627368a"><code>435adee</code></a>
Use &quot;unknown&quot; as type for key path instead of
&quot;PropertyKey&quot;</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/009229d4d7670f06a73c33a2d6eb0ea142aeb1c9"><code>009229d</code></a>
Revert previous assertion as it introduced a regression</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/8561fcbb90a769269e3265bc8868e306cb8d7f82"><code>8561fcb</code></a>
Deep formatter in playground (<a
href="https://redirect.github.com/immutable-js/immutable-js/issues/2099">#2099</a>)</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/96bb20388a6d2c8ce5809f18a017b57ef735d997"><code>96bb203</code></a>
extract repl worker script to a proper file (<a
href="https://redirect.github.com/immutable-js/immutable-js/issues/2097">#2097</a>)</li>
<li><a
href="https://github.com/immutable-js/immutable-js/commit/c81ea7968f2815bf251de91674463a74828c127c"><code>c81ea79</code></a>
Encode code to / decode code from the URL hash. (<a
href="https://redirect.github.com/immutable-js/immutable-js/issues/2096">#2096</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/immutable-js/immutable-js/compare/v5.0.2...v5.1.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=immutable&package-manager=npm_and_yarn&previous-version=5.0.2&new-version=5.1.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>