fix(script): Check for i18n shall consider deconstruct (#7418)
# Motivation

The script that checks if keys are used from the `i18n` file was not
considering deconstruction. For example, in the code we had:

```ts
const {
	transactions: {
		error: { unexpected_transaction_for_hash }
	}
} = get(i18n);
```
		
but key `transactions.error.unexpected_transaction_for_hash` was flagged
as unused.

# Changes

- Adapt script to other possible usage of `i18n` keys.

# Tests

Running it locally, the correct list of keys were raised as unused. We
remove them in this PR as tests for everything working.

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>