test(frontend): mock utxos fee in BtcConvertTokenWizard (#4501)
# Motivation

When we run the tests for BtcConvertTokenWizard there is a warning:


> ```bash
> stderr |
src/frontend/src/tests/btc/components/convert/BtcConvertTokenWizard.spec.ts
> It looks like the agent is trying to make a request that should have
been mocked at Error:
> at Object.transformRequest
(/Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/tests/mocks/identity.mock.ts:11:3)
> at HttpAgent.createReadStateRequest
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1042:27)
> at HttpAgent.readState
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1048:21)
> at
/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/canisterStatus/index.ts:152:12
>     at async Promise.all (index 0)
> at Module.request
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/canisterStatus/index.ts:260:3)
> at HttpAgent.syncTime
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1124:8)
>     at async Promise.all (index 0)
> at Function.create
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/lib/esm/agent/http/index.js:330:9)
> at Module.Y
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/utils/dist/esm/index.js:4:2622)
>   Expected to find result for path time, but instead found nothing.
>   Error: Not implemented
> at Object.transformRequest
(/Users/antonio.ventilii/projects/oisy-wallet/src/frontend/src/tests/mocks/identity.mock.ts:13:8)
> at HttpAgent.createReadStateRequest
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1042:27)
> at HttpAgent.readState
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1048:21)
> at
/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/canisterStatus/index.ts:152:12
>       at async Promise.all (index 0)
> at Module.request
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/canisterStatus/index.ts:260:3)
> at HttpAgent.syncTime
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/src/agent/http/index.ts:1124:8)
>       at async Promise.all (index 0)
> at Function.create
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/agent/lib/esm/agent/http/index.js:330:9)
> at Module.Y
(/Users/antonio.ventilii/projects/oisy-wallet/node_modules/@dfinity/utils/dist/esm/index.js:4:2622)
> 
> ```


This happens because we didn't mock `selectUtxosFee` service.